spring.application.name=ms-gerente
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-gerente
spring.datasource.username=ms-gerente
spring.datasource.password=psql

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/dataMockup.sql

#Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.layout=BaseLayout
