spring.application.name=ms-gerente
server.port=8084


#BD
spring.datasource.url=jdbc:postgresql://db-gerente:5432/ms-gerente
#spring.datasource.url=jdbc:postgresql://localhost:5432/ms-gerente
spring.datasource.username=ms-gerente
spring.datasource.password=psql

## Configs JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

#Dados mockados
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/dataMockup.sql

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Swagger - não esta on ainda mas veremos
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.layout=BaseLayout
