spring.application.name=ms-account

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-account
spring.datasource.username=ms-account
spring.datasource.password=psql

spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.jpa.open-in-view=false